### ISSUE TITLE
RuntimeError: Numpy is not available

### ISSUE THREAD

**Issue by Compstudent** [chavinlo/riffusion-manipulation#11]
I have this error when doing img2audio Python 3.10.6. please help

C:\Users\TheGriot\Desktop\application\Converter\.venv\lib\site-packages\torchaudio\compliance\kaldi.py:22: UserWarning: Failed to initialize NumPy: module compiled against API version 0x10 but this version of numpy is 0xe (Triggered internally at ..\torch\csrc\utils\tensor_numpy.cpp:77.)        
  EPSILON = torch.tensor(torch.finfo(torch.float).eps)
C:\Users\TheGriot\Desktop\application\Converter\.venv\lib\site-packages\torchaudio\backend\utils.py:62: UserWarning: No audio backend is available.
  warnings.warn("No audio backend is available.")
Traceback (most recent call last):
  File "C:\Users\TheGriot\Desktop\application\Converter\riffusion-manipulation\img2audio.py", line 155, in <module>
    wav_bytes, duration_s = wav_bytes_from_spectrogram_image(image, duration=int(args.duration), nmels=int(args.nmels), maxvol=int(args.maxvol), power_for_image=float(args.powerforimage))
  File "C:\Users\TheGriot\Desktop\application\Converter\riffusion-manipulation\img2audio.py", line 112, in wav_bytes_from_spectrogram_image
    samples = waveform_from_spectrogram(
  File "C:\Users\TheGriot\Desktop\application\Converter\riffusion-manipulation\img2audio.py", line 56, in waveform_from_spectrogram
    Sxx_torch = torch.from_numpy(Sxx).to(device)
RuntimeError: Numpy is not available

**Comment by Compstudent** [comment]
ok i just have find right torch for my cuda version i think
